#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: Deep learning models from scratch using C++ and Python
name: Deep learning models from scratch using C++ and Python
description: >- # this means to ignore newlines until "baseurl:"
  Implementing deep learning models in C++ and Python from scratch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexgl-github.github.io"
theme: minima
github_username:  alexgl-github

# Build settings
theme: minima
plugins:
  - jekyll-feed

gems:
  - jekyll-sitemap

plugins:
  - jekyll-sitemap

