title: Deep learning models from scratch using C++ and Python
name: Deep learning models from scratch using C++ and Python
description: >-
  Implementing deep learning models in C++ and Python.
baseurl: ""
url: "https://alexgl-github.github.io"
theme: minima
github_username:  alexgl-github

remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

# Build settings
theme: minima
plugins:
  - jekyll-feed

gems:
  - jekyll-sitemap

plugins:
  - jekyll-sitemap

